Fix a unicode handling bug in webob.exc
When from __future__ import unicode_literals is set, and you create
a request object using Request.blank('/', method='SOME_METHOD_NAME'), and
then a WSGI app handles this request and raises HTTPMethodNotAllowed,
you get this exception:
TypeError: You cannot set the body to a unicode value without a charset

This happens because WSGI app in webob.exc uses a string template
parametrized with things like REQUEST_METHOD, which may happen to
be unicode strings. This produces a unicode body value instead of
expected str value.

Fixed by setting charset when body is unicode.